layout_spectrum: 0.4957447
color:
  saturation: 0.6446809
  brandStrength: 0.6172223
  lightness: 0.3297872
  rhythmicContrast: 0.6085106
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.5957447
name: Chrisbillingsleywrites
